# Generated by Django 3.1.1 on 2020-09-24 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klasa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klasa', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=15)),
                ('nazwisko', models.CharField(max_length=30)),
                ('pesel', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Nauczyciel',
            fields=[
                ('osoba_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='edziennik.osoba')),
                ('tytul', models.CharField(max_length=15)),
            ],
            bases=('edziennik.osoba',),
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_k', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edziennik.klasa')),
                ('id_u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edziennik.osoba')),
            ],
        ),
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena', models.IntegerField()),
                ('waga', models.IntegerField()),
                ('przedmiot', models.CharField(max_length=30)),
                ('id_u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edziennik.osoba')),
            ],
        ),
        migrations.AddField(
            model_name='klasa',
            name='id_u',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edziennik.osoba'),
        ),
    ]
