# Generated by Django 3.1.1 on 2020-09-25 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edziennik', '0003_auto_20200925_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'permissions': (('per_n', 'to jest nauczyciel'),)},
        ),
    ]
