# Generated by Django 3.1.1 on 2020-09-25 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edziennik', '0005_auto_20200925_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'permissions': (('per_u', 'per_n'), ('to jest uczen', 'to jest nauczyciel'))},
        ),
    ]
