# Generated by Django 3.1.1 on 2020-09-25 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edziennik', '0006_auto_20200925_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'permissions': (('per_u', 'to jest uczen'), ('per_n2', 'to jest nauczyciel2'))},
        ),
    ]
