# Generated by Django 3.1.1 on 2020-09-25 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edziennik', '0007_auto_20200925_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'permissions': (('per_n2', 'to jest nauczyciel2'), ('per_u', 'to jest uczen'))},
        ),
    ]
