# Generated by Django 3.1.1 on 2020-09-25 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edziennik', '0008_auto_20200925_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'permissions': (('per_n2', 'to jest nauczyciel3'),)},
        ),
        migrations.DeleteModel(
            name='Nauczyciel',
        ),
    ]
