# Generated by Django 3.1.1 on 2020-09-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edziennik', '0009_auto_20200925_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'permissions': (('nauczyciel', 'nauczyciel v 2.0'),)},
        ),
    ]
