# Generated by Django 3.1.1 on 2020-09-25 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edziennik', '0010_auto_20200925_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='id_u',
            new_name='id_n',
        ),
        migrations.AlterField(
            model_name='osoba',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
