# Generated by Django 3.1.1 on 2020-09-25 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edziennik', '0011_auto_20200925_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klasa',
            name='id_u',
        ),
        migrations.CreateModel(
            name='listaklasy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_k', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='edziennik.klasa')),
                ('id_u', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='edziennik.osoba')),
            ],
        ),
    ]
