# Generated by Django 3.1.1 on 2020-09-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edziennik', '0012_auto_20200925_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='przedmiot',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
