# Generated by Django 3.1.1 on 2020-09-26 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edziennik', '0014_auto_20200926_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocena',
            name='id_n',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='edziennik.plan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ocena',
            name='id_u',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edziennik.osoba'),
        ),
    ]
